# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- Master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install jekyll bundler
    bundle install --retry=3 --jobs=4
  displayName: 'Jekyll install'
 
- script: |
    jekyll build
  displayName: 'Jekyll build'
 
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '_site'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    mv $(Build.ArtifactStagingDirectory)/blog.html $(Build.ArtifactStagingDirectory)/blog/index.html
  displayName: 'Rename blog.html to index.html'

- script: |
    rm $(Build.ArtifactStagingDirectory)/build.yml
  displayName: 'Clean-up files'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs' # 'serviceEndpoint' | 'inputs'. Alias: credsType. Required. Authentication Method. Default: serviceEndpoint.
    #serverEndpoint: # string. Required when credsType = serviceEndpoint. FTP Service Connection. 
    serverUrl: 'ftps://docs.automize-software.com' # string. Required when credsType = inputs. Server URL. 
    username: 'azurepipeline@docs.automize-software.com' # string. Required when credsType = inputs. Username. 
    password: '*[MdKX-HHeVy' # string. Required when credsType = inputs. Password. 
    #implicitFTPS: false # boolean. Use implicit FTPS. Default: false.
    rootDirectory: '$(Build.ArtifactStagingDirectory)/' # string. Alias: rootFolder. Required. Root folder. 
    filePatterns: '**' # string. Required. File patterns. Default: **.
    remoteDirectory: '/' # string. Alias: remotePath. Required. Remote directory. Default: /upload/$(Build.BuildId)/.
  # Advanced
    #enableUtf8: false # boolean. Enable UTF8 support. Default: false. 
    #clean: false # boolean. Delete remote directory. Default: false.
    #cleanContents: true # boolean. Optional. Use when clean = false. Clear remote directory contents. Default: false.
    preservePaths: true # boolean. Preserve file paths. Default: false.
    trustSSL: true # boolean. Trust server certificate. Default: false.
    #customCmds: # string. FTP Commands.
